# Generated by Django 4.0.2 on 2022-08-22 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('df_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationhistory',
            options={'verbose_name_plural': 'Notification history'},
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=13, prefix='', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
