# Generated by Django 4.2.4 on 2023-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_notifications", "0005_alter_pushactioncategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="registration_id",
            field=models.TextField(unique=True, verbose_name="Registration token"),
        ),
    ]
