# Generated by Django 4.2.4 on 2023-09-14 06:55

import df_notifications.fields
import df_notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("df_notifications", "0005_alter_pushactioncategory_options"),
        (
            "test_app",
            "0006_rename_template_postnotificationreminder_template_prefix_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncPostNotificationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    df_notifications.fields.NoMigrationsChoicesField(max_length=255),
                ),
                ("template_prefix", models.CharField(max_length=255)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("is_published_prev", models.BooleanField(default=False, null=True)),
                ("is_published_next", models.BooleanField(default=True)),
                (
                    "history",
                    models.ManyToManyField(
                        blank=True,
                        editable=False,
                        to="df_notifications.notificationhistory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                df_notifications.models.AsyncNotificationMixin,
                df_notifications.models.GenericBase,
                models.Model,
            ),
        ),
    ]
